# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-16 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=264)),
                ('AccessRecords', models.CharField(max_length=264)),
            ],
        ),
    ]
